#!/usr/bin/env python3
"""Prepare a publishable Potree data product and configure the static viewer.

The source LAS/LAZ is never modified.  The output belongs in ``web/pointclouds``
only if its converted size is suitable for GitHub Pages; otherwise upload the
directory to object storage/CDN and use its public metadata.json URL.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
from pathlib import Path

from export_tree_web_data import export_inventory


CONFIG_TEMPLATE = """// Generated by scripts/build_tree_viewer.py\nwindow.TREE_SURVEY_CONFIG = {{\n  title: {title!r},\n  inventoryUrl: \"./data/tree_inventory.json\",\n  pointcloudUrl: {pointcloud_url!r},\n  pointcloudName: {pointcloud_name!r},\n  treeInstanceAttribute: \"instance_id\",\n  coordinateSystem: \"Local survey metres\",\n}};\n"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("inventory", type=Path)
    parser.add_argument("--session", required=True)
    parser.add_argument("--title", default="HKUST Campus Tree Survey")
    parser.add_argument("--source-tile", help="match inventory records to a single converted tile")
    parser.add_argument("--pointcloud", type=Path, help="derived LAS/LAZ to convert")
    parser.add_argument("--potree-converter", default="PotreeConverter")
    parser.add_argument("--encoding", choices=("BROTLI", "UNCOMPRESSED"), default="BROTLI")
    parser.add_argument("--cloud-id", default="hkust_tree_cloud")
    parser.add_argument("--external-metadata-url", help="public metadata.json URL when cloud is hosted outside Pages")
    parser.add_argument("--web-root", type=Path, default=Path("web"))
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    web_root = args.web_root.resolve()
    export_inventory(
        args.inventory,
        web_root / "data" / "tree_inventory.json",
        title=args.title,
        session=args.session,
        source_tile=args.source_tile,
    )
    relative_url = ""
    command: list[str] | None = None
    if args.external_metadata_url:
        relative_url = args.external_metadata_url
    elif args.pointcloud:
        output_dir = web_root / "pointclouds" / args.cloud_id
        relative_url = f"./pointclouds/{args.cloud_id}/metadata.json"
        converter = args.potree_converter
        if not Path(converter).is_file():
            converter = shutil.which(converter) or ""
        if not converter:
            parser.error(
                "PotreeConverter was not found. Build/install it first, or pass "
                "--potree-converter /absolute/path/to/PotreeConverter."
            )
        command = [converter, str(args.pointcloud.resolve()), "-o", str(output_dir), "--encoding", args.encoding]
        if not args.dry_run:
            output_dir.mkdir(parents=True, exist_ok=True)
            subprocess.run(command, check=True)
    (web_root / "app-config.js").write_text(CONFIG_TEMPLATE.format(title=args.title, pointcloud_url=relative_url, pointcloud_name=args.cloud_id), encoding="utf-8")
    print(json.dumps({"web_root": str(web_root), "pointcloud_url": relative_url, "converter_command": command, "dry_run": args.dry_run}, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
