// Generated by scripts/build_tree_viewer.py
window.TREE_SURVEY_CONFIG = {
  title: 'HKUST Campus Tree Survey',
  inventoryUrl: "./data/tree_inventory.json",
  pointcloudUrl: './pointclouds/hkust_s20_tile_x002_y003/metadata.json',
  pointcloudName: 'hkust_s20_tile_x002_y003',
  treeInstanceAttribute: "classification",
  coordinateSystem: "Local survey metres",
};
